import { ApplicationsData } from "./types";

export const applications: ApplicationsData = {
  utilities: [
    {
      id: "1password",
      choco: "1password",
      name: "1Password",
      link: "https://1password.com/",
      winget: "AgileBits.1Password",
    },
    {
      id: "7zip",
      choco: "7zip",
      name: "7-Zip",
      link: "https://www.7-zip.org/",
      winget: "7zip.7zip",
    },
    {
      id: "AdvancedRenamer",
      choco: "advanced-renamer",
      name: "Advanced Renamer",
      link: "https://www.advancedrenamer.com/",
      winget: "HulubuluSoftware.AdvancedRenamer",
    },
    {
      id: "alacritty",
      choco: "alacritty",
      name: "Alacritty Terminal",
      link: "https://alacritty.org/",
      winget: "Alacritty.Alacritty",
    },
    {
      id: "AmbieWhiteNoise",
      choco: "na",
      name: "Ambie White Noise",
      link: "https://ambieapp.com/",
      winget: "9P07XNM5CHP0",
    },
    {
      id: "anydesk",
      choco: "anydesk",
      name: "AnyDesk",
      link: "https://anydesk.com/",
      winget: "AnyDeskSoftwareGmbH.AnyDesk",
    },
    {
      id: "autohotkey",
      choco: "autohotkey",
      name: "AutoHotkey",
      link: "https://www.autohotkey.com/",
      winget: "AutoHotkey.AutoHotkey",
    },
    {
      id: "barrier",
      choco: "barrier",
      name: "Barrier",
      link: "https://github.com/debauchee/barrier",
      winget: "DebaucheeOpenSourceGroup.Barrier",
    },
    {
      id: "bat",
      choco: "bat",
      name: "Bat (Cat)",
      link: "https://github.com/sharkdp/bat",
      winget: "sharkdp.bat",
    },
    {
      id: "bitwarden",
      choco: "bitwarden",
      name: "Bitwarden",
      link: "https://bitwarden.com/",
      winget: "Bitwarden.Bitwarden",
    },
    {
      id: "bleachbit",
      choco: "bleachbit",
      name: "BleachBit",
      link: "https://www.bleachbit.org/",
      winget: "BleachBit.BleachBit",
    },
    {
      id: "BorderlessGaming",
      choco: "borderlessgaming",
      name: "Borderless Gaming",
      link: "https://github.com/Codeusa/Borderless-Gaming",
      winget: "Codeusa.BorderlessGaming",
    },
    {
      id: "bulkcrapuninstaller",
      choco: "bulk-crap-uninstaller",
      name: "Bulk Crap Uninstaller",
      link: "https://www.bcuninstaller.com/",
      winget: "Klocman.BulkCrapUninstaller",
    },
    {
      id: "bulkrenameutility",
      choco: "bulkrenameutility",
      name: "Bulk Rename Utility",
      link: "https://www.bulkrenameutility.co.uk",
      winget: "TGRMNSoftware.BulkRenameUtility",
    },
    {
      id: "capframex",
      choco: "na",
      name: "CapFrameX",
      link: "https://www.capframex.com/",
      winget: "CXWorld.CapFrameX",
    },
    {
      id: "carnac",
      choco: "carnac",
      name: "Carnac",
      link: "https://carnackeys.com/",
      winget: "code52.Carnac",
    },
    {
      id: "CompactGUI",
      choco: "compactgui",
      name: "Compact GUI",
      link: "https://github.com/IridiumIO/CompactGUI",
      winget: "IridiumIO.CompactGUI",
    },
    {
      id: "copyq",
      choco: "copyq",
      name: "CopyQ (Clipboard Manager)",
      link: "https://copyq.readthedocs.io/",
      winget: "hluk.CopyQ",
    },
    {
      id: "cpuz",
      choco: "cpu-z",
      name: "CPU-Z",
      link: "https://www.cpuid.com/softwares/cpu-z.html",
      winget: "CPUID.CPU-Z",
    },
    {
      id: "croc",
      choco: "croc",
      name: "croc",
      link: "https://github.com/schollz/croc",
      winget: "schollz.croc",
    },
    {
      id: "crystaldiskinfo",
      choco: "crystaldiskinfo",
      name: "Crystal Disk Info",
      link: "https://crystalmark.info/en/software/crystaldiskinfo/",
      winget: "CrystalDewWorld.CrystalDiskInfo",
    },
    {
      id: "crystaldiskmark",
      choco: "crystaldiskmark",
      name: "Crystal Disk Mark",
      link: "https://crystalmark.info/en/software/crystaldiskmark/",
      winget: "CrystalDewWorld.CrystalDiskMark",
    },
    {
      id: "deluge",
      choco: "deluge",
      name: "Deluge",
      link: "https://deluge-torrent.org/",
      winget: "DelugeTeam.Deluge",
    },
    {
      id: "devtoys",
      choco: "devtoys",
      name: "DevToys",
      link: "https://devtoys.app/",
      winget: "DevToys-app.DevToys",
    },
    {
      id: "ddu",
      choco: "ddu",
      name: "Display Driver Uninstaller",
      link: "https://www.wagnardsoft.com/display-driver-uninstaller-DDU-",
      winget: "ddu",
    },
    {
      id: "ditto",
      choco: "ditto",
      name: "Ditto",
      link: "https://github.com/sabrogden/Ditto",
      winget: "Ditto.Ditto",
    },
    {
      id: "dropox",
      choco: "na",
      name: "Dropbox",
      link: "https://www.dropbox.com/en_GB/desktop",
      winget: "Dropbox.Dropbox",
    },
    {
      id: "dmt",
      winget: "GNE.DualMonitorTools",
      choco: "dual-monitor-tools",
      name: "Dual Monitor Tools",
      link: "https://dualmonitortool.sourceforge.net/",
    },
    {
      id: "duplicati",
      choco: "duplicati",
      name: "Duplicati",
      link: "https://www.duplicati.com/",
      winget: "Duplicati.Duplicati",
    },
    {
      id: "espanso",
      choco: "espanso",
      name: "Espanso",
      link: "https://espanso.org/",
      winget: "Espanso.Espanso",
    },
    {
      id: "etcher",
      choco: "etcher",
      name: "Etcher USB Creator",
      link: "https://www.balena.io/etcher/",
      winget: "Balena.Etcher",
    },
    {
      id: "esearch",
      choco: "everything",
      name: "Everything Search",
      link: "https://www.voidtools.com/",
      winget: "voidtools.Everything",
    },
    {
      id: "ExifCleaner",
      choco: "na",
      name: "ExifCleaner",
      link: "https://github.com/szTheory/exifcleaner",
      winget: "szTheory.exifcleaner",
    },
    {
      id: "flux",
      choco: "flux",
      name: "F.lux",
      link: "https://justgetflux.com/",
      winget: "flux.flux",
    },
    {
      id: "fancontrol",
      choco: "na",
      name: "FanControl",
      link: "https://getfancontrol.com/",
      winget: "Rem0o.FanControl",
    },
    {
      id: "fastfetch",
      choco: "na",
      name: "Fastfetch",
      link: "https://github.com/fastfetch-cli/fastfetch/",
      winget: "Fastfetch-cli.Fastfetch",
    },
    {
      id: "fileconverter",
      choco: "file-converter",
      name: "File-Converter",
      link: "https://file-converter.io/",
      winget: "AdrienAllard.FileConverter",
    },
    {
      id: "files",
      choco: "files",
      name: "Files",
      link: "https://github.com/files-community/Files",
      winget: "na",
    },
    {
      id: "flow",
      choco: "flow-launcher",
      name: "Flow launcher",
      link: "https://www.flowlauncher.com/",
      winget: "Flow-Launcher.Flow-Launcher",
    },
    {
      id: "ForceAutoHDR",
      choco: "na",
      name: "ForceAutoHDR",
      link: "https://github.com/7gxycn08/ForceAutoHDR",
      winget: "ForceAutoHDR.7gxycn08",
    },
    {
      id: "fzf",
      choco: "fzf",
      name: "Fzf",
      link: "https://github.com/junegunn/fzf/",
      winget: "junegunn.fzf",
    },
    {
      id: "glaryutilities",
      choco: "glaryutilities-free",
      name: "Glary Utilities",
      link: "https://www.glarysoft.com/glary-utilities/",
      winget: "Glarysoft.GlaryUtilities",
    },
    {
      id: "glazewm",
      choco: "na",
      name: "GlazeWM",
      link: "https://github.com/glzr-io/glazewm",
      winget: "glzr-io.glazewm",
    },
    {
      id: "googledrive",
      choco: "googledrive",
      name: "Google Drive",
      link: "https://www.google.com/drive/",
      winget: "Google.GoogleDrive",
    },
    {
      id: "gpuz",
      choco: "gpu-z",
      name: "GPU-Z",
      link: "https://www.techpowerup.com/gpuz/",
      winget: "TechPowerUp.GPU-Z",
    },
    {
      id: "gsudo",
      choco: "gsudo",
      name: "Gsudo",
      link: "https://gerardog.github.io/gsudo/",
      winget: "gerardog.gsudo",
    },
    {
      id: "hwinfo",
      choco: "hwinfo",
      name: "HWiNFO",
      link: "https://www.hwinfo.com/",
      winget: "REALiX.HWiNFO",
    },
    {
      id: "hwmonitor",
      choco: "hwmonitor",
      name: "HWMonitor",
      link: "https://www.cpuid.com/softwares/hwmonitor.html",
      winget: "CPUID.HWMonitor",
    },
    {
      id: "xeheditor",
      choco: "HxD",
      name: "HxD Hex Editor",
      link: "https://mh-nexus.de/en/hxd/",
      winget: "MHNexus.HxD",
    },
    {
      id: "intelpresentmon",
      choco: "na",
      name: "Intel-PresentMon",
      link: "https://game.intel.com/us/stories/intel-presentmon/",
      winget: "Intel.PresentMon.Beta",
    },
    {
      id: "jdownloader",
      choco: "jdownloader",
      name: "JDownloader",
      link: "https://jdownloader.org/",
      winget: "AppWork.JDownloader",
    },
    {
      id: "JoyToKey",
      choco: "joytokey",
      name: "JoyToKey",
      link: "https://joytokey.net/en/",
      winget: "JTKsoftware.JoyToKey",
    },
    {
      id: "jpegview",
      choco: "jpegview",
      name: "JPEG View",
      link: "https://github.com/sylikc/jpegview",
      winget: "sylikc.JPEGView",
    },
    {
      id: "kdeconnect",
      choco: "kdeconnect-kde",
      name: "KDE Connect",
      link: "https://community.kde.org/KDEConnect",
      winget: "KDE.KDEConnect",
    },
    {
      id: "keepass",
      choco: "keepassxc",
      name: "KeePassXC",
      link: "https://keepassxc.org/",
      winget: "KeePassXCTeam.KeePassXC",
    },
    {
      id: "LenovoLegionToolkit",
      choco: "na",
      name: "Lenovo Legion Toolkit",
      link: "https://github.com/BartoszCichecki/LenovoLegionToolkit",
      winget: "BartoszCichecki.LenovoLegionToolkit",
    },
    {
      id: "linkshellextension",
      choco: "linkshellextension",
      name: "Link Shell extension",
      link: "https://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html",
      winget: "HermannSchinagl.LinkShellExtension",
    },
    {
      id: "livelywallpaper",
      choco: "lively",
      name: "Lively Wallpaper",
      link: "https://www.rocksdanister.com/lively/",
      winget: "rocksdanister.LivelyWallpaper",
    },
    {
      id: "localsend",
      choco: "localsend.install",
      name: "LocalSend",
      link: "https://localsend.org/",
      winget: "LocalSend.LocalSend",
    },
    {
      id: "lockhunter",
      choco: "lockhunter",
      name: "LockHunter",
      link: "https://lockhunter.com/",
      winget: "CrystalRich.LockHunter",
    },
    {
      id: "magicwormhole",
      choco: "magic-wormhole",
      name: "Magic Wormhole",
      link: "https://github.com/magic-wormhole/magic-wormhole",
      winget: "magic-wormhole.magic-wormhole",
    },
    {
      id: "malwarebytes",
      choco: "malwarebytes",
      name: "Malwarebytes",
      link: "https://www.malwarebytes.com/",
      winget: "Malwarebytes.Malwarebytes",
    },
    {
      id: "meld",
      choco: "meld",
      name: "Meld",
      link: "https://meldmerge.org/",
      winget: "Meld.Meld",
    },
    {
      id: "monitorian",
      choco: "monitorian",
      name: "Monitorian",
      link: "https://github.com/emoacht/Monitorian",
      winget: "emoacht.Monitorian",
    },
    {
      id: "Motrix",
      choco: "motrix",
      name: "Motrix Download Manager",
      link: "https://motrix.app/",
      winget: "agalwood.Motrix",
    },
    {
      id: "msedgeredirect",
      choco: "msedgeredirect",
      name: "MSEdgeRedirect",
      link: "https://github.com/rcmaehl/MSEdgeRedirect",
      winget: "rcmaehl.MSEdgeRedirect",
    },
    {
      id: "msiafterburner",
      choco: "msiafterburner",
      name: "MSI Afterburner",
      link: "https://www.msi.com/Landing/afterburner",
      winget: "Guru3D.Afterburner",
    },
    {
      id: "nanazip",
      choco: "nanazip",
      name: "NanaZip",
      link: "https://github.com/M2Team/NanaZip",
      winget: "M2Team.NanaZip",
    },
    {
      id: "neofetchwin",
      choco: "na",
      name: "Neofetch",
      link: "https://github.com/nepnep39/neofetch-win",
      winget: "nepnep.neofetch-win",
    },
    {
      id: "nextclouddesktop",
      choco: "nextcloud-client",
      name: "Nextcloud Desktop",
      link: "https://nextcloud.com/install/#install-clients",
      winget: "Nextcloud.NextcloudDesktop",
    },
    {
      id: "nilesoftShell",
      choco: "nilesoft-shell",
      name: "Nilesoft Shell",
      link: "https://nilesoft.org/",
      winget: "Nilesoft.Shell",
    },
    {
      id: "nushell",
      choco: "nushell",
      name: "Nushell",
      link: "https://www.nushell.sh/",
      winget: "Nushell.Nushell",
    },
    {
      id: "nvclean",
      choco: "na",
      name: "NVCleanstall",
      link: "https://www.techpowerup.com/nvcleanstall/",
      winget: "TechPowerUp.NVCleanstall",
    },
    {
      id: "OFGB",
      choco: "ofgb",
      name: "OFGB (Oh Frick Go Back)",
      link: "https://github.com/xM4ddy/OFGB",
      winget: "xM4ddy.OFGB",
    },
    {
      id: "OPAutoClicker",
      choco: "autoclicker",
      name: "OPAutoClicker",
      link: "https://www.opautoclicker.com",
      winget: "OPAutoClicker.OPAutoClicker",
    },
    {
      id: "openshell",
      choco: "open-shell",
      name: "Open Shell (Start Menu)",
      link: "https://github.com/Open-Shell/Open-Shell-Menu",
      winget: "Open-Shell.Open-Shell-Menu",
    },
    {
      id: "openhashtab",
      choco: "openhashtab",
      name: "OpenHashTab",
      link: "https://github.com/namazso/OpenHashTab/",
      winget: "namazso.OpenHashTab",
    },
    {
      id: "openrgb",
      choco: "openrgb",
      name: "OpenRGB",
      link: "https://openrgb.org/",
      winget: "CalcProgrammer1.OpenRGB",
    },
    {
      id: "OVirtualBox",
      choco: "virtualbox",
      name: "Oracle VirtualBox",
      link: "https://www.virtualbox.org/",
      winget: "Oracle.VirtualBox",
    },
    {
      id: "orcaslicer",
      choco: "orcaslicer",
      name: "OrcaSlicer",
      link: "https://github.com/SoftFever/OrcaSlicer",
      winget: "SoftFever.OrcaSlicer",
    },
    {
      id: "ownclouddesktop",
      choco: "owncloud-client",
      name: "ownCloud Desktop",
      link: "https://owncloud.com/desktop-app/",
      winget: "ownCloud.ownCloudDesktop",
    },
    {
      id: "parsec",
      choco: "parsec",
      name: "Parsec",
      link: "https://parsec.app/",
      winget: "Parsec.Parsec",
    },
    {
      id: "peazip",
      choco: "peazip",
      name: "PeaZip",
      link: "https://peazip.github.io/",
      winget: "Giorgiotani.Peazip",
    },
    {
      id: "processlasso",
      choco: "plasso",
      name: "Process Lasso",
      link: "https://bitsum.com/",
      winget: "BitSum.ProcessLasso",
    },
    {
      id: "prucaslicer",
      choco: "prusaslicer",
      name: "PrusaSlicer",
      link: "https://www.prusa3d.com/prusaslicer/",
      winget: "Prusa3d.PrusaSlicer",
    },
    {
      id: "qbittorrent",
      choco: "qbittorrent",
      name: "qBittorrent",
      link: "https://www.qbittorrent.org/",
      winget: "qBittorrent.qBittorrent",
    },
    {
      id: "quicklook",
      choco: "quicklook",
      name: "Quicklook",
      link: "https://github.com/QL-Win/QuickLook",
      winget: "QL-Win.QuickLook",
    },
    {
      id: "rainmeter",
      choco: "na",
      name: "Rainmeter",
      link: "https://www.rainmeter.net/",
      winget: "Rainmeter.Rainmeter",
    },
    {
      id: "piimager",
      choco: "rpi-imager",
      name: "Raspberry Pi Imager",
      link: "https://www.raspberrypi.com/software/",
      winget: "RaspberryPiFoundation.RaspberryPiImager",
    },
    {
      id: "revo",
      choco: "revo-uninstaller",
      name: "Revo Uninstaller",
      link: "https://www.revouninstaller.com/",
      winget: "RevoUninstaller.RevoUninstaller",
    },
    {
      id: "ripgrep",
      choco: "ripgrep",
      name: "Ripgrep",
      link: "https://github.com/BurntSushi/ripgrep/",
      winget: "BurntSushi.ripgrep.MSVC",
    },
    {
      id: "rufus",
      choco: "rufus",
      name: "Rufus Imager",
      link: "https://rufus.ie/",
      winget: "Rufus.Rufus",
    },
    {
      id: "sagethumbs",
      choco: "sagethumbs",
      name: "SageThumbs",
      link: "https://sagethumbs.en.lo4d.com/windows",
      winget: "CherubicSoftware.SageThumbs",
    },
    {
      id: "samsungmagician",
      choco: "samsung-magician",
      name: "Samsung Magician",
      link: "https://semiconductor.samsung.com/consumer-storage/magician/",
      winget: "Samsung.SamsungMagician",
    },
    {
      id: "sandboxie",
      choco: "sandboxie",
      name: "Sandboxie Plus",
      link: "https://github.com/sandboxie-plus/Sandboxie",
      winget: "Sandboxie.Plus",
    },
    {
      id: "signalrgb",
      choco: "na",
      name: "SignalRGB",
      link: "https://www.signalrgb.com/",
      winget: "WhirlwindFX.SignalRgb",
    },
    {
      id: "sdio",
      choco: "sdio",
      name: "Snappy Driver Installer Origin",
      link: "https://www.glenn.delahoy.com/snappy-driver-installer-origin/",
      winget: "GlennDelahoy.SnappyDriverInstallerOrigin",
    },
    {
      id: "spacedrive",
      choco: "na",
      name: "Spacedrive File Manager",
      link: "https://www.spacedrive.com/",
      winget: "spacedrive.Spacedrive",
    },
    {
      id: "spacesniffer",
      choco: "spacesniffer",
      name: "SpaceSniffer",
      link: "http://www.uderzo.it/main_products/space_sniffer/",
      winget: "UderzoSoftware.SpaceSniffer",
    },
    {
      id: "superf4",
      choco: "superf4",
      name: "SuperF4",
      link: "https://stefansundin.github.io/superf4/",
      winget: "StefanSundin.Superf4",
    },
    {
      id: "syncthingtray",
      choco: "syncthingtray",
      name: "Syncthingtray",
      link: "https://github.com/Martchus/syncthingtray",
      winget: "Martchus.syncthingtray",
    },
    {
      id: "synctrayzor",
      choco: "synctrayzor",
      name: "SyncTrayzor",
      link: "https://github.com/canton7/SyncTrayzor/",
      winget: "SyncTrayzor.SyncTrayzor",
    },
    {
      id: "tabby",
      choco: "tabby",
      name: "Tabby.sh",
      link: "https://tabby.sh/",
      winget: "Eugeny.Tabby",
    },
    {
      id: "tailscale",
      choco: "tailscale",
      name: "Tailscale",
      link: "https://tailscale.com/",
      winget: "tailscale.tailscale",
    },
    {
      id: "teamviewer",
      choco: "teamviewer9",
      name: "TeamViewer",
      link: "https://www.teamviewer.com/",
      winget: "TeamViewer.TeamViewer",
    },
    {
      id: "TeraCopy",
      choco: "TeraCopy",
      name: "TeraCopy",
      link: "https://codesector.com/teracopy",
      winget: "CodeSector.TeraCopy",
    },
    {
      id: "tightvnc",
      choco: "TightVNC",
      name: "TightVNC",
      link: "https://www.tightvnc.com/",
      winget: "GlavSoft.TightVNC",
    },
    {
      id: "tixati",
      choco: "tixati.portable",
      name: "Tixati",
      link: "https://www.tixati.com/",
      winget: "Tixati.Tixati.Portable",
    },
    {
      id: "totalcommander",
      choco: "TotalCommander",
      name: "Total Commander",
      link: "https://www.ghisler.com/",
      winget: "Ghisler.TotalCommander",
    },
    {
      id: "ttaskbar",
      choco: "translucenttb",
      name: "Translucent Taskbar",
      link: "https://github.com/TranslucentTB/TranslucentTB",
      winget: "9PF4KZ2VN4W9",
    },
    {
      id: "transmission",
      choco: "transmission",
      name: "Transmission",
      link: "https://transmissionbt.com/",
      winget: "Transmission.Transmission",
    },
    {
      id: "treesize",
      choco: "treesizefree",
      name: "TreeSize Free",
      link: "https://www.jam-software.com/treesize_free/",
      winget: "JAMSoftware.TreeSize.Free",
    },
    {
      id: "twinkletray",
      choco: "twinkle-tray",
      name: "Twinkle Tray",
      link: "https://twinkletray.com/",
      winget: "xanderfrangos.twinkletray",
    },
    {
      id: "ultravnc",
      choco: "ultravnc",
      name: "UltraVNC",
      link: "https://uvnc.com/",
      winget: "uvncbvba.UltraVnc",
    },
    {
      id: "wingetui",
      choco: "wingetui",
      name: "UniGetUI",
      link: "https://www.marticliment.com/wingetui/",
      winget: "MartiCliment.UniGetUI",
    },
    {
      id: "vistaswitcher",
      choco: "na",
      name: "VistaSwitcher",
      link: "https://www.ntwind.com/freeware/vistaswitcher.html",
      winget: "ntwind.VistaSwitcher",
    },
    {
      id: "wazuh",
      choco: "wazuh-agent",
      name: "Wazuh.",
      link: "https://wazuh.com/",
      winget: "Wazuh.WazuhAgent",
    },
    {
      id: "Windhawk",
      choco: "windhawk",
      name: "Windhawk",
      link: "https://windhawk.net",
      winget: "RamenSoftware.Windhawk",
    },
    {
      id: "WindowGrid",
      choco: "windowgrid",
      name: "WindowGrid",
      link: "http://windowgrid.net/",
      winget: "na",
    },
    {
      id: "autodarkmode",
      choco: "auto-dark-mode",
      name: "Windows Auto Dark Mode",
      link: "https://github.com/AutoDarkMode/Windows-Auto-Night-Mode",
      winget: "Armin2208.WindowsAutoNightMode",
    },
    {
      id: "windowsfirewallcontrol",
      choco: "windowsfirewallcontrol",
      name: "Windows Firewall Control",
      link: "https://www.binisoft.org/wfc",
      winget: "BiniSoft.WindowsFirewallControl",
    },
    {
      id: "windowspchealth",
      choco: "na",
      name: "Windows PC Health Check",
      link: "https://support.microsoft.com/en-us/windows/how-to-use-the-pc-health-check-app-9c8abd9b-03ba-4e67-81ef-36f37caa7844",
      winget: "Microsoft.WindowsPCHealthCheck",
    },
    {
      id: "winpaletter",
      choco: "WinPaletter",
      name: "WinPaletter",
      link: "https://github.com/Abdelrhman-AK/WinPaletter",
      winget: "Abdelrhman-AK.WinPaletter",
    },
    {
      id: "winrar",
      choco: "winrar",
      name: "WinRAR",
      link: "https://www.win-rar.com/",
      winget: "RARLab.WinRAR",
    },
    {
      id: "WiseProgramUninstaller",
      choco: "na",
      name: "Wise Program Uninstaller (WiseCleaner)",
      link: "https://www.wisecleaner.com/wise-program-uninstaller.html",
      winget: "WiseCleaner.WiseProgramUninstaller",
    },
    {
      id: "wisetoys",
      choco: "na",
      name: "WiseToys",
      link: "https://toys.wisecleaner.com/",
      winget: "WiseCleaner.WiseToys",
    },
    {
      id: "wizfile",
      choco: "na",
      name: "WizFile",
      link: "https://antibody-software.com/wizfile/",
      winget: "AntibodySoftware.WizFile",
    },
    {
      id: "wiztree",
      choco: "wiztree",
      name: "WizTree",
      link: "https://wiztreefree.com/",
      winget: "AntibodySoftware.WizTree",
    },
    {
      id: "xnview",
      choco: "xnview",
      name: "XnView classic",
      link: "https://www.xnview.com/en/xnview/",
      winget: "XnSoft.XnView.Classic",
    },
    {
      id: "xdm",
      choco: "xdm",
      name: "Xtreme Download Manager",
      link: "https://xtremedownloadmanager.com/",
      winget: "subhra74.XtremeDownloadManager",
    },
    {
      id: "zerotierone",
      choco: "zerotier-one",
      name: "ZeroTier One",
      link: "https://zerotier.com/",
      winget: "ZeroTier.ZeroTierOne",
    },
    {
      id: "zoomit",
      choco: "na",
      name: "ZoomIt",
      link: "https://learn.microsoft.com/en-us/sysinternals/downloads/zoomit",
      winget: "Microsoft.Sysinternals.ZoomIt",
    },
    {
      id: "zoxide",
      choco: "zoxide",
      name: "Zoxide",
      link: "https://github.com/ajeetdsouza/zoxide",
      winget: "ajeetdsouza.zoxide",
    },
  ],
  document: [
    {
      id: "adobe",
      choco: "adobereader",
      name: "Adobe Acrobat Reader",
      link: "https://www.adobe.com/acrobat/pdf-reader.html",
      winget: "Adobe.Acrobat.Reader.64-bit",
    },
    {
      id: "affine",
      choco: "na",
      name: "AFFiNE",
      link: "https://affine.pro/",
      winget: "ToEverything.AFFiNE",
    },
    {
      id: "anki",
      choco: "anki",
      name: "Anki",
      link: "https://apps.ankiweb.net/",
      winget: "Anki.Anki",
    },
    {
      id: "openoffice",
      choco: "openoffice",
      name: "Apache OpenOffice",
      link: "https://www.openoffice.org/",
      winget: "Apache.OpenOffice",
    },
    {
      id: "calibre",
      choco: "calibre",
      name: "Calibre",
      link: "https://calibre-ebook.com/",
      winget: "calibre.calibre",
    },
    {
      id: "foxpdfeditor",
      choco: "na",
      name: "Foxit PDF Editor",
      link: "https://www.foxit.com/pdf-editor/",
      winget: "Foxit.PhantomPDF",
    },
    {
      id: "foxpdfreader",
      choco: "foxitreader",
      name: "Foxit PDF Reader",
      link: "https://www.foxit.com/pdf-reader/",
      winget: "Foxit.FoxitReader",
    },
    {
      id: "joplin",
      choco: "joplin",
      name: "Joplin (FOSS Notes)",
      link: "https://joplinapp.org/",
      winget: "Joplin.Joplin",
    },
    {
      id: "libreoffice",
      choco: "libreoffice-fresh",
      name: "LibreOffice",
      link: "https://www.libreoffice.org/",
      winget: "TheDocumentFoundation.LibreOffice",
    },
    {
      id: "logseq",
      choco: "logseq",
      name: "Logseq",
      link: "https://logseq.com/",
      winget: "Logseq.Logseq",
    },
    {
      id: "masscode",
      choco: "na",
      name: "massCode (Snippet Manager)",
      link: "https://masscode.io/",
      winget: "antonreshetov.massCode",
    },
    {
      id: "naps2",
      choco: "naps2",
      name: "NAPS2 (Document Scanner)",
      link: "https://www.naps2.com/",
      winget: "Cyanfish.NAPS2",
    },
    {
      id: "notepadplus",
      choco: "notepadplusplus",
      name: "Notepad++",
      link: "https://notepad-plus-plus.org/",
      winget: "Notepad++.Notepad++",
    },
    {
      id: "obsidian",
      choco: "obsidian",
      name: "Obsidian",
      link: "https://obsidian.md/",
      winget: "Obsidian.Obsidian",
    },
    {
      id: "okular",
      choco: "okular",
      name: "Okular",
      link: "https://okular.kde.org/",
      winget: "KDE.Okular",
    },
    {
      id: "onlyoffice",
      choco: "onlyoffice",
      name: "ONLYOffice Desktop",
      link: "https://www.onlyoffice.com/desktop.aspx",
      winget: "ONLYOFFICE.DesktopEditors",
    },
    {
      id: "pdf24creator",
      choco: "pdf24",
      name: "PDF24 creator",
      link: "https://tools.pdf24.org/en/",
      winget: "geeksoftwareGmbH.PDF24Creator",
    },
    {
      id: "pdfgear",
      choco: "na",
      name: "PDFgear",
      link: "https://www.pdfgear.com/",
      winget: "PDFgear.PDFgear",
    },
    {
      id: "pdfsam",
      choco: "pdfsam",
      name: "PDFsam Basic",
      link: "https://pdfsam.org/",
      winget: "PDFsam.PDFsam",
    },
    {
      id: "simplenote",
      choco: "simplenote",
      name: "simplenote",
      link: "https://simplenote.com/",
      winget: "Automattic.Simplenote",
    },
    {
      id: "sumatra",
      choco: "sumatrapdf",
      name: "Sumatra PDF",
      link: "https://www.sumatrapdfreader.org/free-pdf-reader.html",
      winget: "SumatraPDF.SumatraPDF",
    },
    {
      id: "winmerge",
      choco: "winmerge",
      name: "WinMerge",
      link: "https://winmerge.org/",
      winget: "WinMerge.WinMerge",
    },
    {
      id: "xournal",
      choco: "xournalplusplus",
      name: "Xournal++",
      link: "https://xournalpp.github.io/",
      winget: "Xournal++.Xournal++",
    },
    {
      id: "zim",
      choco: "zim",
      name: "Zim Desktop Wiki",
      link: "https://zim-wiki.org/",
      winget: "Zimwiki.Zim",
    },
    {
      id: "znote",
      choco: "na",
      name: "Znote",
      link: "https://znote.io/",
      winget: "alagrede.znote",
    },
    {
      id: "zotero",
      choco: "zotero",
      name: "Zotero",
      link: "https://www.zotero.org/",
      winget: "DigitalScholar.Zotero",
    },
  ],
  proTools: [
    {
      id: "advancedip",
      choco: "advanced-ip-scanner",
      name: "Advanced IP Scanner",
      link: "https://www.advanced-ip-scanner.com/",
      winget: "Famatech.AdvancedIPScanner",
    },
    {
      id: "angryipscanner",
      choco: "angryip",
      name: "Angry IP Scanner",
      link: "https://angryip.org/",
      winget: "angryziber.AngryIPScanner",
    },
    {
      id: "efibooteditor",
      choco: "na",
      name: "EFI Boot Editor",
      link: "https://www.easyuefi.com/",
      winget: "EFIBootEditor.EFIBootEditor",
    },
    {
      id: "heidisql",
      choco: "heidisql",
      name: "HeidiSQL",
      link: "https://www.heidisql.com/",
      winget: "HeidiSQL.HeidiSQL",
    },
    {
      id: "mremoteng",
      choco: "mremoteng",
      name: "mRemoteNG",
      link: "https://mremoteng.org/",
      winget: "mRemoteNG.mRemoteNG",
    },
    {
      id: "mullvadvpn",
      choco: "mullvad-app",
      name: "Mullvad VPN",
      link: "https://github.com/mullvad/mullvadvpn-app",
      winget: "MullvadVPN.MullvadVPN",
    },
    {
      id: "netbird",
      choco: "netbird",
      name: "NetBird",
      link: "https://netbird.io/",
      winget: "netbird",
    },
    {
      id: "nmap",
      choco: "nmap",
      name: "Nmap",
      link: "https://nmap.org/",
      winget: "Insecure.Nmap",
    },
    {
      id: "OpenVPN",
      choco: "openvpn-connect",
      name: "OpenVPN Connect",
      link: "https://openvpn.net/",
      winget: "OpenVPNTechnologies.OpenVPNConnect",
    },
    {
      id: "Portmaster",
      choco: "portmaster",
      name: "Portmaster",
      link: "https://safing.io/",
      winget: "Safing.Portmaster",
    },
    {
      id: "putty",
      choco: "putty",
      name: "PuTTY",
      link: "https://www.chiark.greenend.org.uk/~sgtatham/putty/",
      winget: "PuTTY.PuTTY",
    },
    {
      id: "rustdesk",
      choco: "rustdesk.portable",
      name: "RustDesk",
      link: "https://rustdesk.com/",
      winget: "RustDesk.RustDesk",
    },
    {
      id: "simplewall",
      choco: "simplewall",
      name: "Simplewall",
      link: "https://github.com/henrypp/simplewall",
      winget: "Henry++.simplewall",
    },
    {
      id: "ventoy",
      choco: "ventoy",
      name: "Ventoy",
      link: "https://www.ventoy.net/",
      winget: "Ventoy.Ventoy",
    },
    {
      id: "winscp",
      choco: "winscp",
      name: "WinSCP",
      link: "https://winscp.net/",
      winget: "WinSCP.WinSCP",
    },
    {
      id: "wireguard",
      choco: "wireguard",
      name: "WireGuard",
      link: "https://www.wireguard.com/",
      winget: "WireGuard.WireGuard",
    },
    {
      id: "wireshark",
      choco: "wireshark",
      name: "Wireshark",
      link: "https://www.wireshark.org/",
      winget: "WiresharkFoundation.Wireshark",
    },
    {
      id: "xpipe",
      choco: "xpipe",
      name: "XPipe",
      link: "https://xpipe.io/",
      winget: "xpipe-io.xpipe",
    },
  ],
  multimediaTools: [
    {
      id: "aimp",
      choco: "aimp",
      name: "AIMP (Music Player)",
      link: "https://www.aimp.ru/",
      winget: "AIMP.AIMP",
    },
    {
      id: "audacity",
      choco: "audacity",
      name: "Audacity",
      link: "https://www.audacityteam.org/",
      winget: "Audacity.Audacity",
    },
    {
      id: "blender",
      choco: "blender",
      name: "Blender (3D Graphics)",
      link: "https://www.blender.org/",
      winget: "BlenderFoundation.Blender",
    },
    {
      id: "clementine",
      choco: "clementine",
      name: "Clementine",
      link: "https://www.clementine-player.org/",
      winget: "Clementine.Clementine",
    },
    {
      id: "darktable",
      choco: "darktable",
      name: "darktable",
      link: "https://www.darktable.org/install/",
      winget: "darktable.darktable",
    },
    {
      id: "digikam",
      choco: "digikam",
      name: "digiKam",
      link: "https://www.digikam.org/",
      winget: "KDE.digikam",
    },
    {
      id: "eartrumpet",
      choco: "eartrumpet",
      name: "EarTrumpet (Audio)",
      link: "https://eartrumpet.app/",
      winget: "File-New-Project.EarTrumpet",
    },
    {
      id: "EqualizerAPO",
      choco: "equalizerapo",
      name: "Equalizer APO",
      link: "https://sourceforge.net/projects/equalizerapo",
      winget: "na",
    },
    {
      id: "ffmpeg",
      choco: "ffmpeg-full",
      name: "FFmpeg (full)",
      link: "https://ffmpeg.org/",
      winget: "Gyan.FFmpeg",
    },
    {
      id: "firealpaca",
      choco: "firealpaca",
      name: "Fire Alpaca",
      link: "https://firealpaca.com/",
      winget: "FireAlpaca.FireAlpaca",
    },
    {
      id: "flameshot",
      choco: "flameshot",
      name: "Flameshot (Screenshots)",
      link: "https://flameshot.org/",
      winget: "Flameshot.Flameshot",
    },
    {
      id: "foobar",
      choco: "foobar2000",
      name: "foobar2000 (Music Player)",
      link: "https://www.foobar2000.org/",
      winget: "PeterPawlowski.foobar2000",
    },
    {
      id: "freecad",
      choco: "freecad",
      name: "FreeCAD",
      link: "https://www.freecadweb.org/",
      winget: "FreeCAD.FreeCAD",
    },
    {
      id: "fxsound",
      choco: "fxsound",
      name: "FxSound",
      link: "https://www.fxsound.com/",
      winget: "FxSound.FxSound",
    },
    {
      id: "gimp",
      choco: "gimp",
      name: "GIMP (Image Editor)",
      link: "https://www.gimp.org/",
      winget: "GIMP.GIMP",
    },
    {
      id: "greenshot",
      choco: "greenshot",
      name: "Greenshot (Screenshots)",
      link: "https://getgreenshot.org/",
      winget: "Greenshot.Greenshot",
    },
    {
      id: "handbrake",
      choco: "handbrake",
      name: "HandBrake",
      link: "https://handbrake.fr/",
      winget: "HandBrake.HandBrake",
    },
    {
      id: "harmonoid",
      choco: "na",
      name: "Harmonoid",
      link: "https://harmonoid.com/",
      winget: "Harmonoid.Harmonoid",
    },
    {
      id: "imageglass",
      choco: "imageglass",
      name: "ImageGlass (Image Viewer)",
      link: "https://imageglass.org/",
      winget: "DuongDieuPhap.ImageGlass",
    },
    {
      id: "imgburn",
      choco: "imgburn",
      name: "ImgBurn",
      link: "https://www.imgburn.com/",
      winget: "LIGHTNINGUK.ImgBurn",
    },
    {
      id: "inkscape",
      choco: "inkscape",
      name: "Inkscape",
      link: "https://inkscape.org/",
      winget: "Inkscape.Inkscape",
    },
    {
      id: "itunes",
      choco: "itunes",
      name: "iTunes",
      link: "https://www.apple.com/itunes/",
      winget: "Apple.iTunes",
    },
    {
      id: "jellyfinmediaplayer",
      choco: "jellyfin-media-player",
      name: "Jellyfin Media Player",
      link: "https://github.com/jellyfin/jellyfin-media-player",
      winget: "Jellyfin.JellyfinMediaPlayer",
    },
    {
      id: "jellyfinserver",
      choco: "jellyfin",
      name: "Jellyfin Server",
      link: "https://jellyfin.org/",
      winget: "Jellyfin.Server",
    },
    {
      id: "klite",
      choco: "k-litecodecpack-standard",
      name: "K-Lite Codec Standard",
      link: "https://www.codecguide.com/",
      winget: "CodecGuide.K-LiteCodecPack.Standard",
    },
    {
      id: "kdenlive",
      choco: "kdenlive",
      name: "Kdenlive (Video Editor)",
      link: "https://kdenlive.org/",
      winget: "KDE.Kdenlive",
    },
    {
      id: "kicad",
      choco: "na",
      name: "Kicad",
      link: "https://www.kicad.org/",
      winget: "KiCad.KiCad",
    },
    {
      id: "kodi",
      choco: "kodi",
      name: "Kodi Media Center",
      link: "https://kodi.tv/",
      winget: "XBMCFoundation.Kodi",
    },
    {
      id: "krita",
      choco: "krita",
      name: "Krita (Image Editor)",
      link: "https://krita.org/en/features/",
      winget: "KDE.Krita",
    },
    {
      id: "lightshot",
      choco: "lightshot",
      name: "Lightshot (Screenshots)",
      link: "https://app.prntscr.com/",
      winget: "Skillbrains.Lightshot",
    },
    {
      id: "mpchc",
      choco: "mpc-hc-clsid2",
      name: "Media Player Classic - Home Cinema",
      link: "https://github.com/clsid2/mpc-hc/",
      winget: "clsid2.mpc-hc",
    },
    {
      id: "ModernFlyouts",
      choco: "na",
      name: "Modern Flyouts",
      link: "https://github.com/ModernFlyouts-Community/ModernFlyouts/",
      winget: "ModernFlyouts.ModernFlyouts",
    },
    {
      id: "mp3tag",
      choco: "mp3tag",
      name: "Mp3tag (Metadata Audio Editor)",
      link: "https://www.mp3tag.de/en/",
      winget: "Mp3tag.Mp3tag",
    },
    {
      id: "musescore",
      choco: "musescore",
      name: "MuseScore",
      link: "https://musescore.org/en",
      winget: "Musescore.Musescore",
    },
    {
      id: "musicbee",
      choco: "musicbee",
      name: "MusicBee (Music Player)",
      link: "https://getmusicbee.com/",
      winget: "MusicBee.MusicBee",
    },
    {
      id: "nditools",
      choco: "na",
      name: "NDI Tools",
      link: "https://ndi.video/",
      winget: "NDI.NDITools",
    },
    {
      id: "nglide",
      choco: "na",
      name: "nGlide (3dfx compatibility)",
      link: "https://www.zeus-software.com/downloads/nglide",
      winget: "ZeusSoftware.nGlide",
    },
    {
      id: "nomacs",
      choco: "nomacs",
      name: "Nomacs (Image viewer)",
      link: "https://nomacs.org/",
      winget: "nomacs.nomacs",
    },
    {
      id: "obs",
      choco: "obs-studio",
      name: "OBS Studio",
      link: "https://obsproject.com/",
      winget: "OBSProject.OBSStudio",
    },
    {
      id: "openscad",
      choco: "openscad",
      name: "OpenSCAD",
      link: "https://www.openscad.org/",
      winget: "OpenSCAD.OpenSCAD",
    },
    {
      id: "Paintdotnet",
      choco: "paint.net",
      name: "Paint.NET",
      link: "https://www.getpaint.net/",
      winget: "dotPDN.PaintDotNet",
    },
    {
      id: "plexdesktop",
      choco: "plex",
      name: "Plex Desktop",
      link: "https://www.plex.tv",
      winget: "Plex.Plex",
    },
    {
      id: "plex",
      choco: "plexmediaserver",
      name: "Plex Media Server",
      link: "https://www.plex.tv/your-media/",
      winget: "Plex.PlexMediaServer",
    },
    {
      id: "qgis",
      choco: "qgis",
      name: "QGIS",
      link: "https://qgis.org/en/site/",
      winget: "OSGeo.QGIS",
    },
    {
      id: "sharex",
      choco: "sharex",
      name: "ShareX (Screenshots)",
      link: "https://getsharex.com/",
      winget: "ShareX.ShareX",
    },
    {
      id: "Shotcut",
      choco: "na",
      name: "Shotcut",
      link: "https://shotcut.org/",
      winget: "Meltytech.Shotcut",
    },
    {
      id: "smplayer",
      choco: "smplayer",
      name: "SMPlayer",
      link: "https://www.smplayer.info",
      winget: "SMPlayer.SMPlayer",
    },
    {
      id: "spotify",
      choco: "spotify",
      name: "Spotify",
      link: "https://www.spotify.com/",
      winget: "Spotify.Spotify",
    },
    {
      id: "spotube",
      choco: "spotube",
      name: "Spotube",
      link: "https://github.com/KRTirtho/spotube",
      winget: "KRTirtho.Spotube",
    },
    {
      id: "strawberry",
      choco: "strawberrymusicplayer",
      name: "Strawberry (Music Player)",
      link: "https://www.strawberrymusicplayer.org/",
      winget: "StrawberryMusicPlayer.Strawberry",
    },
    {
      id: "stremio",
      winget: "Stremio.Stremio",
      choco: "stremio",
      name: "Stremio",
      link: "https://www.stremio.com/",
    },
    {
      id: "SubtitleEdit",
      choco: "na",
      name: "Subtitle Edit",
      link: "https://github.com/SubtitleEdit/subtitleedit",
      winget: "Nikse.SubtitleEdit",
    },
    {
      id: "tagscanner",
      choco: "tagscanner",
      name: "TagScanner (Tag Scanner)",
      link: "https://www.xdlab.ru/en/",
      winget: "SergeySerkov.TagScanner",
    },
    {
      id: "tidal",
      choco: "na",
      name: "Tidal",
      link: "https://tidal.com/",
      winget: "9NNCB5BS59PH",
    },
    {
      id: "videomass",
      choco: "na",
      name: "Videomass",
      link: "https://jeanslack.github.io/Videomass/",
      winget: "GianlucaPernigotto.Videomass",
    },
    {
      id: "vlc",
      choco: "vlc",
      name: "VLC (Video Player)",
      link: "https://www.videolan.org/vlc/",
      winget: "VideoLAN.VLC",
    },
    {
      id: "voicemeeter",
      choco: "voicemeeter",
      name: "Voicemeeter (Audio)",
      link: "https://voicemeeter.com/",
      winget: "VB-Audio.Voicemeeter",
    },
    {
      id: "VoicemeeterPotato",
      choco: "voicemeeter-potato",
      name: "Voicemeeter Potato",
      link: "https://voicemeeter.com/",
      winget: "VB-Audio.Voicemeeter.Potato",
    },
    {
      id: "ytdlp",
      choco: "yt-dlp",
      name: "Yt-dlp",
      link: "https://github.com/yt-dlp/yt-dlp",
      winget: "yt-dlp.yt-dlp",
    },
  ],
  development: [
    {
      id: "Aegisub",
      choco: "aegisub",
      name: "Aegisub",
      link: "https://github.com/Aegisub/Aegisub",
      winget: "Aegisub.Aegisub",
    },
    {
      id: "java11",
      choco: "corretto11jdk",
      name: "Amazon Corretto 11 (LTS)",
      link: "https://aws.amazon.com/corretto",
      winget: "Amazon.Corretto.11.JDK",
    },
    {
      id: "java17",
      choco: "corretto17jdk",
      name: "Amazon Corretto 17 (LTS)",
      link: "https://aws.amazon.com/corretto",
      winget: "Amazon.Corretto.17.JDK",
    },
    {
      id: "java21",
      choco: "corretto21jdk",
      name: "Amazon Corretto 21 (LTS)",
      link: "https://aws.amazon.com/corretto",
      winget: "Amazon.Corretto.21.JDK",
    },
    {
      id: "java8",
      choco: "corretto8jdk",
      name: "Amazon Corretto 8 (LTS)",
      link: "https://aws.amazon.com/corretto",
      winget: "Amazon.Corretto.8.JDK",
    },
    {
      id: "anaconda3",
      choco: "anaconda3",
      name: "Anaconda",
      link: "https://www.anaconda.com/products/distribution",
      winget: "Anaconda.Anaconda3",
    },
    {
      id: "clink",
      choco: "clink",
      name: "Clink",
      link: "https://mridgers.github.io/clink/",
      winget: "chrisant996.Clink",
    },
    {
      id: "cmake",
      choco: "cmake",
      name: "CMake",
      link: "https://cmake.org/",
      winget: "Kitware.CMake",
    },
    {
      id: "MuEditor",
      choco: "na",
      name: "Code With Mu (Mu Editor)",
      link: "https://codewith.mu/",
      winget: "Mu.Mu",
    },
    {
      id: "DaxStudio",
      choco: "daxstudio",
      name: "DaxStudio",
      link: "https://daxstudio.org/",
      winget: "DaxStudio.DaxStudio",
    },
    {
      id: "dockerdesktop",
      choco: "docker-desktop",
      name: "Docker Desktop",
      link: "https://www.docker.com/products/docker-desktop",
      winget: "Docker.DockerDesktop",
    },
    {
      id: "temurin",
      choco: "temurin",
      name: "Eclipse Temurin",
      link: "https://adoptium.net/temurin/",
      winget: "EclipseAdoptium.Temurin.21.JDK",
    },
    {
      id: "fnm",
      choco: "fnm",
      name: "Fast Node Manager",
      link: "https://github.com/Schniz/fnm",
      winget: "Schniz.fnm",
    },
    {
      id: "Fork",
      choco: "git-fork",
      name: "Fork",
      link: "https://git-fork.com/",
      winget: "Fork.Fork",
    },
    {
      id: "git",
      choco: "git",
      name: "Git",
      link: "https://git-scm.com/",
      winget: "Git.Git",
    },
    {
      id: "gitbutler",
      choco: "na",
      name: "Git Butler",
      link: "https://gitbutler.com/",
      winget: "GitButler.GitButler",
    },
    {
      id: "gitextensions",
      choco: "git;gitextensions",
      name: "Git Extensions",
      link: "https://gitextensions.github.io/",
      winget: "GitExtensionsTeam.GitExtensions",
    },
    {
      id: "githubcli",
      choco: "git;gh",
      name: "GitHub CLI",
      link: "https://cli.github.com/",
      winget: "GitHub.cli",
    },
    {
      id: "githubdesktop",
      choco: "git;github-desktop",
      name: "GitHub Desktop",
      link: "https://desktop.github.com/",
      winget: "GitHub.GitHubDesktop",
    },
    {
      id: "gitify",
      choco: "na",
      name: "Gitify",
      link: "https://www.gitify.io/",
      winget: "Gitify.Gitify",
    },
    {
      id: "gitkrakenclient",
      choco: "gitkraken",
      name: "GitKraken Client",
      link: "https://www.gitkraken.com/git-client",
      winget: "Axosoft.GitKraken",
    },
    {
      id: "golang",
      choco: "golang",
      name: "Go",
      link: "https://go.dev/",
      winget: "GoLang.Go",
    },
    {
      id: "godotengine",
      choco: "godot",
      name: "Godot Engine",
      link: "https://godotengine.org/",
      winget: "GodotEngine.GodotEngine",
    },
    {
      id: "helix",
      choco: "helix",
      name: "Helix",
      link: "https://helix-editor.com/",
      winget: "Helix.Helix",
    },
    {
      id: "jetbrains",
      choco: "jetbrainstoolbox",
      name: "Jetbrains Toolbox",
      link: "https://www.jetbrains.com/toolbox/",
      winget: "JetBrains.Toolbox",
    },
    {
      id: "lazygit",
      choco: "lazygit",
      name: "Lazygit",
      link: "https://github.com/jesseduffield/lazygit/",
      winget: "JesseDuffield.lazygit",
    },
    {
      id: "miniconda",
      choco: "miniconda3",
      name: "Miniconda",
      link: "https://docs.conda.io/projects/miniconda",
      winget: "Anaconda.Miniconda3",
    },
    {
      id: "neovim",
      choco: "neovim",
      name: "Neovim",
      link: "https://neovim.io/",
      winget: "Neovim.Neovim",
    },
    {
      id: "nvm",
      choco: "nvm",
      name: "Node Version Manager",
      link: "https://github.com/coreybutler/nvm-windows",
      winget: "CoreyButler.NVMforWindows",
    },
    {
      id: "nodejs",
      choco: "nodejs",
      name: "NodeJS",
      link: "https://nodejs.org/",
      winget: "OpenJS.NodeJS",
    },
    {
      id: "nodejslts",
      choco: "nodejs-lts",
      name: "NodeJS LTS",
      link: "https://nodejs.org/",
      winget: "OpenJS.NodeJS.LTS",
    },
    {
      id: "posh",
      choco: "oh-my-posh",
      name: "Oh My Posh (Prompt)",
      link: "https://ohmyposh.dev/",
      winget: "JanDeDobbeleer.OhMyPosh",
    },
    {
      id: "pixi",
      choco: "pixi",
      name: "Pixi",
      link: "https://pixi.sh",
      winget: "prefix-dev.pixi",
    },
    {
      id: "postman",
      choco: "postman",
      name: "Postman",
      link: "https://www.postman.com/",
      winget: "Postman.Postman",
    },
    {
      id: "PulsarEdit",
      choco: "pulsar",
      name: "Pulsar",
      link: "https://pulsar-edit.dev/",
      winget: "Pulsar-Edit.Pulsar",
    },
    {
      id: "pyenvwin",
      choco: "pyenv-win",
      name: "Python Version Manager (pyenv-win)",
      link: "https://pyenv-win.github.io/pyenv-win/",
      winget: "na",
    },
    {
      id: "python3",
      choco: "python",
      name: "Python3",
      link: "https://www.python.org/",
      winget: "Python.Python.3.12",
    },
    {
      id: "rustlang",
      choco: "rust",
      name: "Rust",
      link: "https://www.rust-lang.org/",
      winget: "Rustlang.Rust.MSVC",
    },
    {
      id: "starship",
      choco: "starship",
      name: "Starship (Shell Prompt)",
      link: "https://starship.rs/",
      winget: "starship",
    },
    {
      id: "sublimemerge",
      choco: "sublimemerge",
      name: "Sublime Merge",
      link: "https://www.sublimemerge.com/",
      winget: "SublimeHQ.SublimeMerge",
    },
    {
      id: "sublimetext",
      choco: "sublimetext4",
      name: "Sublime Text",
      link: "https://www.sublimetext.com/",
      winget: "SublimeHQ.SublimeText.4",
    },
    {
      id: "swift",
      choco: "na",
      name: "Swift toolchain",
      link: "https://www.swift.org/",
      winget: "Swift.Toolchain",
    },
    {
      id: "Thonny",
      choco: "thonny",
      name: "Thonny Python IDE",
      link: "https://github.com/thonny/thonny",
      winget: "AivarAnnamaa.Thonny",
    },
    {
      id: "unity",
      choco: "unityhub",
      name: "Unity Game Engine",
      link: "https://unity.com/",
      winget: "Unity.UnityHub",
    },
    {
      id: "vagrant",
      choco: "vagrant",
      name: "Vagrant",
      link: "https://www.vagrantup.com/",
      winget: "Hashicorp.Vagrant",
    },
    {
      id: "visualstudio",
      choco: "visualstudio2022community",
      name: "Visual Studio 2022",
      link: "https://visualstudio.microsoft.com/",
      winget: "Microsoft.VisualStudio.2022.Community",
    },
    {
      id: "vscode",
      choco: "vscode",
      name: "VS Code",
      link: "https://code.visualstudio.com/",
      winget: "Microsoft.VisualStudioCode",
    },
    {
      id: "vscodium",
      choco: "vscodium",
      name: "VS Codium",
      link: "https://vscodium.com/",
      winget: "VSCodium.VSCodium",
    },
    {
      id: "wezterm",
      choco: "wezterm",
      name: "Wezterm",
      link: "https://wezfurlong.org/wezterm/index.html",
      winget: "wez.wezterm",
    },
    {
      id: "yarn",
      choco: "yarn",
      name: "Yarn",
      link: "https://yarnpkg.com/",
      winget: "Yarn.Yarn",
    },
  ],
  microsoftTools: [
    {
      id: "dotnet3",
      choco: "dotnetcore3-desktop-runtime",
      name: ".NET Desktop Runtime 3.1",
      link: "https://dotnet.microsoft.com/download/dotnet/3.1",
      winget: "Microsoft.DotNet.DesktopRuntime.3_1",
    },
    {
      id: "dotnet5",
      choco: "dotnet-5.0-runtime",
      name: ".NET Desktop Runtime 5",
      link: "https://dotnet.microsoft.com/download/dotnet/5.0",
      winget: "Microsoft.DotNet.DesktopRuntime.5",
    },
    {
      id: "dotnet6",
      choco: "dotnet-6.0-runtime",
      name: ".NET Desktop Runtime 6",
      link: "https://dotnet.microsoft.com/download/dotnet/6.0",
      winget: "Microsoft.DotNet.DesktopRuntime.6",
    },
    {
      id: "dotnet7",
      choco: "dotnet-7.0-runtime",
      name: ".NET Desktop Runtime 7",
      link: "https://dotnet.microsoft.com/download/dotnet/7.0",
      winget: "Microsoft.DotNet.DesktopRuntime.7",
    },
    {
      id: "dotnet8",
      choco: "dotnet-8.0-runtime",
      name: ".NET Desktop Runtime 8",
      link: "https://dotnet.microsoft.com/download/dotnet/8.0",
      winget: "Microsoft.DotNet.DesktopRuntime.8",
    },
    {
      id: "dotnet9",
      choco: "dotnet-9.0-runtime",
      name: ".NET Desktop Runtime 9",
      link: "https://dotnet.microsoft.com/download/dotnet/9.0",
      winget: "Microsoft.DotNet.DesktopRuntime.9",
    },
    {
      id: "autoruns",
      choco: "autoruns",
      name: "Autoruns",
      link: "https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns",
      winget: "Microsoft.Sysinternals.Autoruns",
    },
    {
      id: "azuredatastudio",
      choco: "azure-data-studio",
      name: "Microsoft Azure Data Studio",
      link: "https://docs.microsoft.com/sql/azure-data-studio/what-is-azure-data-studio",
      winget: "Microsoft.AzureDataStudio",
    },
    {
      id: "sqlmanagementstudio",
      choco: "sql-server-management-studio",
      name: "Microsoft SQL Server Management Studio",
      link: "https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16",
      winget: "Microsoft.SQLServerManagementStudio",
    },
    {
      id: "nuget",
      choco: "nuget.commandline",
      name: "NuGet",
      link: "https://www.nuget.org/",
      winget: "Microsoft.NuGet",
    },
    {
      id: "onedrive",
      choco: "onedrive",
      name: "OneDrive",
      link: "https://onedrive.live.com/",
      winget: "Microsoft.OneDrive",
    },
    {
      id: "powerautomate",
      choco: "powerautomatedesktop",
      name: "Power Automate",
      link: "https://www.microsoft.com/en-us/power-platform/products/power-automate",
      winget: "Microsoft.PowerAutomateDesktop",
    },
    {
      id: "powerbi",
      choco: "powerbi",
      name: "Power BI",
      link: "https://www.microsoft.com/en-us/power-platform/products/power-bi/",
      winget: "Microsoft.PowerBI",
    },
    {
      id: "powershell",
      choco: "powershell-core",
      name: "PowerShell",
      link: "https://github.com/PowerShell/PowerShell",
      winget: "Microsoft.PowerShell",
    },
    {
      id: "powertoys",
      choco: "powertoys",
      name: "PowerToys",
      link: "https://github.com/microsoft/PowerToys",
      winget: "Microsoft.PowerToys",
    },
    {
      id: "rdcman",
      choco: "rdcman",
      name: "RDCMan",
      link: "https://learn.microsoft.com/en-us/sysinternals/downloads/rdcman",
      winget: "Microsoft.Sysinternals.RDCMan",
    },
    {
      id: "processmonitor",
      choco: "procexp",
      name: "SysInternals Process Monitor",
      link: "https://docs.microsoft.com/en-us/sysinternals/downloads/procmon",
      winget: "Microsoft.Sysinternals.ProcessMonitor",
    },
    {
      id: "tcpview",
      choco: "tcpview",
      name: "SysInternals TCPView",
      link: "https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview",
      winget: "Microsoft.Sysinternals.TCPView",
    },
    {
      id: "vc2015_32",
      choco: "na",
      name: "Visual C++ 2015-2022 32-bit",
      link: "https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads",
      winget: "Microsoft.VCRedist.2015+.x86",
    },
    {
      id: "vc2015_64",
      choco: "na",
      name: "Visual C++ 2015-2022 64-bit",
      link: "https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads",
      winget: "Microsoft.VCRedist.2015+.x64",
    },
    {
      id: "terminal",
      choco: "microsoft-windows-terminal",
      name: "Windows Terminal",
      link: "https://aka.ms/terminal",
      winget: "Microsoft.WindowsTerminal",
    },
  ],
  browsers: [
    {
      id: "arc",
      choco: "na",
      name: "Arc",
      link: "https://arc.net/",
      winget: "TheBrowserCompany.Arc",
    },
    {
      id: "brave",
      choco: "brave",
      name: "Brave",
      link: "https://www.brave.com",
      winget: "Brave.Brave",
    },
    {
      id: "chrome",
      choco: "googlechrome",
      name: "Chrome",
      link: "https://www.google.com/chrome/",
      winget: "Google.Chrome",
    },
    {
      id: "chromium",
      choco: "chromium",
      name: "Chromium",
      link: "https://github.com/Hibbiki/chromium-win64",
      winget: "Hibbiki.Chromium",
    },
    {
      id: "edge",
      choco: "microsoft-edge",
      name: "Edge",
      link: "https://www.microsoft.com/edge",
      winget: "Microsoft.Edge",
    },
    {
      id: "falkon",
      choco: "falkon",
      name: "Falkon",
      link: "https://www.falkon.org/",
      winget: "KDE.Falkon",
    },
    {
      id: "firefox",
      choco: "firefox",
      name: "Firefox",
      link: "https://www.mozilla.org/en-US/firefox/new/",
      winget: "Mozilla.Firefox",
    },
    {
      id: "firefoxesr",
      choco: "FirefoxESR",
      name: "Firefox ESR",
      link: "https://www.mozilla.org/en-US/firefox/enterprise/",
      winget: "Mozilla.Firefox.ESR",
    },
    {
      id: "floorp",
      choco: "na",
      name: "Floorp",
      link: "https://floorp.app/",
      winget: "Ablaze.Floorp",
    },
    {
      id: "librewolf",
      choco: "librewolf",
      name: "LibreWolf",
      link: "https://librewolf-community.gitlab.io/",
      winget: "LibreWolf.LibreWolf",
    },
    {
      id: "mullvadbrowser",
      choco: "na",
      name: "Mullvad Browser",
      link: "https://mullvad.net/browser",
      winget: "MullvadVPN.MullvadBrowser",
    },
    {
      id: "PaleMoon",
      choco: "paleMoon",
      name: "PaleMoon",
      link: "https://www.palemoon.org/download.shtml",
      winget: "MoonchildProductions.PaleMoon",
    },
    {
      id: "thorium",
      choco: "na",
      name: "Thorium Browser AVX2",
      link: "https://thorium.rocks/",
      winget: "Alex313031.Thorium.AVX2",
    },
    {
      id: "tor",
      choco: "tor-browser",
      name: "Tor Browser",
      link: "https://www.torproject.org/",
      winget: "TorProject.TorBrowser",
    },
    {
      id: "ungoogled",
      choco: "ungoogled-chromium",
      name: "Ungoogled",
      link: "https://github.com/Eloston/ungoogled-chromium",
      winget: "eloston.ungoogled-chromium",
    },
    {
      id: "vivaldi",
      choco: "vivaldi",
      name: "Vivaldi",
      link: "https://vivaldi.com/",
      winget: "Vivaldi.Vivaldi",
    },
    {
      id: "waterfox",
      choco: "waterfox",
      name: "Waterfox",
      link: "https://www.waterfox.net/",
      winget: "Waterfox.Waterfox",
    },
    {
      id: "ZenBrowser",
      choco: "na",
      name: "Zen Browser",
      link: "https://zen-browser.app/",
      winget: "Zen-Team.Zen-Browser",
    },
  ],
  games: [
    {
      id: "cemu",
      choco: "cemu",
      name: "Cemu",
      link: "https://cemu.info/",
      winget: "Cemu.Cemu",
    },
    {
      id: "clonehero",
      choco: "na",
      name: "Clone Hero",
      link: "https://clonehero.net/",
      winget: "CloneHeroTeam.CloneHero",
    },
    {
      id: "eaapp",
      choco: "ea-app",
      name: "EA App",
      link: "https://www.ea.com/ea-app",
      winget: "ElectronicArts.EADesktop",
    },
    {
      id: "emulationstation",
      choco: "emulationstation",
      name: "Emulation Station",
      link: "https://emulationstation.org/",
      winget: "Emulationstation.Emulationstation",
    },
    {
      id: "epicgames",
      choco: "epicgameslauncher",
      name: "Epic Games Launcher",
      link: "https://www.epicgames.com/store/en-US/",
      winget: "EpicGames.EpicGamesLauncher",
    },
    {
      id: "geforcenow",
      choco: "nvidia-geforce-now",
      name: "GeForce NOW",
      link: "https://www.nvidia.com/en-us/geforce-now/",
      winget: "Nvidia.GeForceNow",
    },
    {
      id: "gog",
      choco: "goggalaxy",
      name: "GOG Galaxy",
      link: "https://www.gog.com/galaxy",
      winget: "GOG.Galaxy",
    },
    {
      id: "heroiclauncher",
      choco: "na",
      name: "Heroic Games Launcher",
      link: "https://heroicgameslauncher.com/",
      winget: "HeroicGamesLauncher.HeroicGamesLauncher",
    },
    {
      id: "itch",
      choco: "itch",
      name: "Itch.io",
      link: "https://itch.io/",
      winget: "ItchIo.Itch",
    },
    {
      id: "moonlight",
      choco: "moonlight-qt",
      name: "Moonlight/GameStream Client",
      link: "https://moonlight-stream.org/",
      winget: "MoonlightGameStreamingProject.Moonlight",
    },
    {
      id: "playnite",
      choco: "playnite",
      name: "Playnite",
      link: "https://playnite.link/",
      winget: "Playnite.Playnite",
    },
    {
      id: "prismlauncher",
      choco: "prismlauncher",
      name: "Prism Launcher",
      link: "https://prismlauncher.org/",
      winget: "PrismLauncher.PrismLauncher",
    },
    {
      id: "psremoteplay",
      choco: "ps-remote-play",
      name: "PS Remote Play",
      link: "https://remoteplay.dl.playstation.net/remoteplay/lang/gb/",
      winget: "PlayStation.PSRemotePlay",
    },
    {
      id: "sidequest",
      choco: "sidequest",
      name: "SideQuestVR",
      link: "https://sidequestvr.com/",
      winget: "SideQuestVR.SideQuest",
    },
    {
      id: "steam",
      choco: "steam-client",
      name: "Steam",
      link: "https://store.steampowered.com/about/",
      winget: "Valve.Steam",
    },
    {
      id: "sunshine",
      choco: "sunshine",
      name: "Sunshine/GameStream Server",
      link: "https://github.com/LizardByte/Sunshine",
      winget: "LizardByte.Sunshine",
    },
    {
      id: "TcNoAccSwitcher",
      choco: "tcno-acc-switcher",
      name: "TCNO Account Switcher",
      link: "https://github.com/TCNOco/TcNo-Acc-Switcher",
      winget: "TechNobo.TcNoAccountSwitcher",
    },
    {
      id: "ubisoft",
      choco: "ubisoft-connect",
      name: "Ubisoft Connect",
      link: "https://ubisoftconnect.com/",
      winget: "Ubisoft.Connect",
    },
    {
      id: "vrdesktopstreamer",
      choco: "na",
      name: "Virtual Desktop Streamer",
      link: "https://www.vrdesktop.net/",
      winget: "VirtualDesktop.Streamer",
    },
    {
      id: "xemu",
      choco: "na",
      name: "XEMU",
      link: "https://xemu.app/",
      winget: "xemu-project.xemu",
    },
  ],
  communications: [
    {
      id: "betterbird",
      choco: "betterbird",
      name: "Betterbird",
      link: "https://www.betterbird.eu/",
      winget: "Betterbird.Betterbird",
    },
    {
      id: "chatterino",
      choco: "chatterino",
      name: "Chatterino",
      link: "https://www.chatterino.com/",
      winget: "ChatterinoTeam.Chatterino",
    },
    {
      id: "discord",
      choco: "discord",
      name: "Discord",
      link: "https://discord.com/",
      winget: "Discord.Discord",
    },
    {
      id: "matrix",
      choco: "element-desktop",
      name: "Element",
      link: "https://element.io/",
      winget: "Element.Element",
    },
    {
      id: "ferdium",
      choco: "ferdium",
      name: "Ferdium",
      link: "https://ferdium.org/",
      winget: "Ferdium.Ferdium",
    },
    {
      id: "guilded",
      choco: "na",
      name: "Guilded",
      link: "https://www.guilded.gg/",
      winget: "Guilded.Guilded",
    },
    {
      id: "hexchat",
      choco: "hexchat",
      name: "Hexchat",
      link: "https://hexchat.github.io/",
      winget: "HexChat.HexChat",
    },
    {
      id: "jami",
      choco: "jami",
      name: "Jami",
      link: "https://jami.net/",
      winget: "SFLinux.Jami",
    },
    {
      id: "linphone",
      choco: "linphone",
      name: "Linphone",
      link: "https://www.linphone.org/",
      winget: "BelledonneCommunications.Linphone",
    },
    {
      id: "qtox",
      choco: "qtox",
      name: "QTox",
      link: "https://qtox.github.io/",
      winget: "Tox.qTox",
    },
    {
      id: "revolt",
      choco: "na",
      name: "Revolt",
      link: "https://revolt.chat/",
      winget: "Revolt.RevoltDesktop",
    },
    {
      id: "session",
      choco: "session",
      name: "Session",
      link: "https://getsession.org/",
      winget: "Oxen.Session",
    },
    {
      id: "signal",
      choco: "signal",
      name: "Signal",
      link: "https://signal.org/",
      winget: "OpenWhisperSystems.Signal",
    },
    {
      id: "skype",
      choco: "skype",
      name: "Skype",
      link: "https://www.skype.com/",
      winget: "Microsoft.Skype",
    },
    {
      id: "slack",
      choco: "slack",
      name: "Slack",
      link: "https://slack.com/",
      winget: "SlackTechnologies.Slack",
    },
    {
      id: "teams",
      choco: "microsoft-teams",
      name: "Teams",
      link: "https://www.microsoft.com/en-us/microsoft-teams/group-chat-software",
      winget: "Microsoft.Teams",
    },
    {
      id: "telegram",
      choco: "telegram",
      name: "Telegram",
      link: "https://telegram.org/",
      winget: "Telegram.TelegramDesktop",
    },
    {
      id: "thunderbird",
      choco: "thunderbird",
      name: "Thunderbird",
      link: "https://www.thunderbird.net/",
      winget: "Mozilla.Thunderbird",
    },
    {
      id: "unigram",
      choco: "na",
      name: "Unigram",
      link: "https://unigramdev.github.io/",
      winget: "Telegram.Unigram",
    },
    {
      id: "vesktop",
      choco: "na",
      name: "Vesktop",
      link: "https://github.com/Vencord/Vesktop",
      winget: "Vencord.Vesktop",
    },
    {
      id: "viber",
      choco: "viber",
      name: "Viber",
      link: "https://www.viber.com/",
      winget: "Viber.Viber",
    },
    {
      id: "zoom",
      choco: "zoom",
      name: "Zoom",
      link: "https://zoom.us/",
      winget: "Zoom.Zoom",
    },
    {
      id: "zulip",
      choco: "zulip",
      name: "Zulip",
      link: "https://zulipchat.com/",
      winget: "Zulip.Zulip",
    },
  ],
};
